dist: xenial
sudo: false
language: php

php:
  - '7.2'
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - currentDir=$(pwd)
  - tempDir=$(mktemp -d)
  - curl -sSL -o "$tempDir/cphalcon" https://codeload.github.com/phalcon/cphalcon/tar.gz/v3.4.3
  - tar -C "$tempDir" -xzf "$tempDir/cphalcon"
  - cd "$tempDir"/cphalcon-3.4.3/build
  - ./install
  - cd "$currentDir"
  - rm -rf "$tempDir"
  - echo 'extension=phalcon.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install: travis_retry composer install

script:
  - ./vendor/bin/phpunit --configuration=phpunit.xml.dist --testsuite=Unit
  - ./vendor/bin/phpunit --configuration=phpunit.xml.dist --testsuite=Functional

jobs:
  include:
    - stage: Analyse
      name: "Code coverage analysis"
      before_script:
        - if [[ ! $(php -m | grep -i xdebug) ]]; then echo "xdebug is required for code coverage"; exit 1; fi
      script:
        - ./vendor/bin/phpunit --configuration=phpunit.xml.dist --coverage-clover=./clover.xml --testsuite=Unit
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml

    - stage: Analyse
      name: "Code style analysis"
      script:
        - ./vendor/bin/phpcs

    - stage: Analyse
      name: "Static analysis"
      script:
        - ./vendor/bin/phpstan analyse --level=max --configuration=phpstan-src.neon.dist src
        - ./vendor/bin/phpstan analyse --level=max --configuration=phpstan-tests.neon.dist tests
